### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by PhatAdam** [jelledruyts/InspectorGadget#5]
when i cat /etc/resolv.conf a resolver appears to be be placed in the container on our behalf, my options_ are set to include mine -- but its adding a third. 

would also be huge to have traceroute, and ping available from the shell.  just an idea :) love your project.    I could contribute paypal or venmo for some help.

**Comment by jelledruyts** [comment]
Thanks @PhatAdam for the kind words! Now the container is built on top of ASP.NET's base image (see https://github.com/jelledruyts/InspectorGadget/blob/main/WebApp/Linux.Dockerfile) which has minimal dependencies installed to reduce possible attack vectors. Running random processes on the container OS isn't really the core use case for the web app here and I don't really want to maintain my own base image either :-)

You can always install additional packages if you want (as long as you keep your specific container _instance_ alive anyway), but also take care that you enable some kind of auth on the web app, otherwise anyone can come in and do whatever they want (I always disable the Process Run gadget for that reason with [DisableProcessRun=true](https://github.com/jelledruyts/InspectorGadget?tab=readme-ov-file#configuration)).
